
services:
  amonic:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/amonic
    environment:
      - DB_HOST=database
      - DB_NAME=amonic_airlines
      - DB_USER=my_user
      - DB_PASS=pass

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      database:
        condition: service_healthy

  database:
    hostname: dbname
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'amonic_airlines'
      MYSQL_USER: 'my_user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 160